language: python
python:
  - '3.6'
  - '3.7'
install:
  - make install
script:
  - make test-all
deploy:
  provider: pypi
  user: __token__
  password:
    secure: CejgsfuAMPd6hFBWQvIDE4H9l3fqBklqa9VHvVqhnUMtxTq2YMtyyBBCgckyCjHe4dzUe+amp1WmqDMOflqWoiGMiX4VREFwg/Aot1b0bABugsRH1Lg9npYvVeKDrTldFJpdE2sX4j0DdzU3FPnnAR1QXJELBUpI/bjIn/HnNhX7Y+2DgzJxc2lgUpBZYcg/szc9DCgQwthUxOvb0iKUeqh70A4Pvr42e0Xdn7abez56zMVlGUlWokKLozNfz/wA4QsjcjqzlZtPnlX10pff6mb/o+Pd2E1Sur2tqR6D5R84sBNFO1uyzSd9vdhSpZHWpxoi+baXTEnt5/zwu/Pa9qwhyJK92iNYX9MC1cUpVwvwzd5WbPwMznSkU/YVgcjgH0rbbGvjy1F6yhTGAPpN2umsqQkBC191WESphanuTfTKHyPiDNq3TWJJUxK+icQyRCM3ABI99qzwvCvvzKh70SJqYFuEccV8RzZIuCK9vg5fULhE7ugxhxmLga18VHuAj6FbDuq/8VxrwPWPMO7gMp8lt1eTT+ak0IqnreykiS/42oabF81wND04Moj2q84cx4IRXz34sYFkkmvy+VEFq0UnpEiQGamiPYVc0fDQD9iBdLRiRDOlkwshM44kuvsvggQkKCIfRNHFOvA+xHv1RlxFVn0YbK/q6OzIRVWSfYQ=
  on:
    tags: true
  distributions: sdist bdist_wheel
  skip_existing: true
notifications:
  slack:
    secure: nV6gKjt5z8Fx5gfC9ysrV9/ZBnDtbS2Lccs8plXQmyqEVlQhHt8z5gXbKwa9BMlV4wSuK4d7swVpC6Uz4L07/VV4pZF/0UTcODz2rVqbpTUrO1B8z6gqhyAy6XaRs9DNoJ6R0RqZhUEQPi2MsUh7FdNpFPONVObtq3SrmI3ztVtROn3M3uOVWjVXfF/FnY+DwlpQ4Jdja1ZMxfyVadf4lx+Ac3N8cxs1X4K0se3IZslnS/gv6VRDVh5d5lgBc2MT1WTnIDIFyqEICdVdG6zs4I6TJuaK57NlOfCPekBTCN5wW2qnlfl6XxRwTG/276FMNjWohLm5gNYvnrHx+CVcmNuIJ0BpJ2gv4pV+aHVy46/wqPk0YbEIXABO+qbCvBfI2YcPSHQx5H4DlmB5euDPud4x3FiO0UpQ8yrou9UhQqnojWhTJcdaNSomDEW+uSRGu23AmXFFQg6L0+7pKjXKrLaVEk6DHMcWE04/9V44VbhI48iHMU4ARMTnTmlaPQHBnHlNhLzoTLEX8L0mHJKqD/uexH2w1EWmwDQirM6wy42HpW9Yph9SXCvjGPSbGQ5dvSdMmoziBjeDUkt67R4S7zTfAgWwRxZUlUyY99E0wCm+RGlF2qCrv7ocq2YPwhjNHqL++2d2A3sAfG825Y+0qZcb7gDvbPmb5rwRU325FLw=
