language: python
python:
  - '3.6'
  - '3.7'
install:
  - make install
script:
  - make test-all
deploy:
  provider: pypi
  user: __token__
  password:
    secure: BCCKuBFkf9udKHESl/JLk5P04QSZNjIJcZwFhYTwwsFRcUpNIkOhmGM/RvYyHclijqz7IAQfupnWt+k9FCQcht0HuaUC19hCJM0g0kBZct5MU+ji/ypEQS35dd1dzuAaCyGq9M55hNbuTLwcnrk3Ve9tPX3lKx2fHGwgyi9LgmsZIt0pOFnFx160IkmXJFyaxjqVIcrte7LlhnEpZW0Zp++mdYaEGopIqauCqi5cXv8tuap3CtzkRIJJEcpyeR0yvRapbp08BieB2hGfbXZ/S/VixV3FPpf4me6r9MAPCYo+7X2dQV7p5nZkebC3FrAvrdxDK+tS6tDc4JdyjmGPaSsybnt+Ddr5oxrpjeCPdK8BfBLlbpmxtYVEKnI7/JfcIikqj8xSAQseVyPFIMKnzBkNotI0+UT5gAkTeFFNIX9Jaivc91J+g2XAbYW5eIb3itxACx+js70Ffagr93nXQlp8HUXOEqJfniBEpqrJV6DH7YZo3GfVMdFwe9zIX6iJcIfPZ7jlMabTMPxDjVc/4WieZJCpaH8Atx6lEIFS/D3q7Nr1wvpYlFqgz2hUSuUeYH39r75fNGFKihCZY8B82xfFt7KH76LJIlG83wDGFbGHAFfTyaIW9VOO1yN6/busQ1cTk4EF4dDGGldQoGUhFbBYcscZhfNGe5edJkeK6bI=
  on:
    tags: true
  distributions: sdist bdist_wheel
  skip_existing: true
notifications:
  slack:
    secure: nV6gKjt5z8Fx5gfC9ysrV9/ZBnDtbS2Lccs8plXQmyqEVlQhHt8z5gXbKwa9BMlV4wSuK4d7swVpC6Uz4L07/VV4pZF/0UTcODz2rVqbpTUrO1B8z6gqhyAy6XaRs9DNoJ6R0RqZhUEQPi2MsUh7FdNpFPONVObtq3SrmI3ztVtROn3M3uOVWjVXfF/FnY+DwlpQ4Jdja1ZMxfyVadf4lx+Ac3N8cxs1X4K0se3IZslnS/gv6VRDVh5d5lgBc2MT1WTnIDIFyqEICdVdG6zs4I6TJuaK57NlOfCPekBTCN5wW2qnlfl6XxRwTG/276FMNjWohLm5gNYvnrHx+CVcmNuIJ0BpJ2gv4pV+aHVy46/wqPk0YbEIXABO+qbCvBfI2YcPSHQx5H4DlmB5euDPud4x3FiO0UpQ8yrou9UhQqnojWhTJcdaNSomDEW+uSRGu23AmXFFQg6L0+7pKjXKrLaVEk6DHMcWE04/9V44VbhI48iHMU4ARMTnTmlaPQHBnHlNhLzoTLEX8L0mHJKqD/uexH2w1EWmwDQirM6wy42HpW9Yph9SXCvjGPSbGQ5dvSdMmoziBjeDUkt67R4S7zTfAgWwRxZUlUyY99E0wCm+RGlF2qCrv7ocq2YPwhjNHqL++2d2A3sAfG825Y+0qZcb7gDvbPmb5rwRU325FLw=
